export { getAuthorizedAdminNavigationSections } from "./admin-navigation";

export {
  canAccessRoute,
  MOCK_AUTH_COOKIE,
  canAccessAdminSection,
  canManageAdminSection,
  canManageBooks,
  canManageBorrowings,
  canManageCategories,
  canManageInventory,
  canManageUsers,
  canViewFinancials,
  hasAdminAccess,
  buildSignOutHref,
  buildMockAuthorizeHref,
  buildMockSignInHref,
  buildMockSignOutHref,
  createAppAuthUser,
  createAuthenticatedAuthState,
  createGuestAuthState,
  createMockAuthState,
  getCurrentRole,
  getCurrentStatus,
  getCurrentUser,
  getDefaultRedirectForRole,
  getMockCurrentUser,
  getRouteAuthorization,
  isSuperAdmin,
  isStaff,
  isAdmin,
  isEmployee,
  isFinancial,
  isAuthenticated,
  isMember,
  isSuspended,
  isMockAuthenticatedRole,
  isMockAuthRole,
  mockAuthenticatedRoles,
  sanitizeRedirectTo,
  type AppAuthenticatedRole,
  type AppAuthRole,
  type AppAuthSource,
  type AppAuthState,
  type AppAuthUser,
  type AppRouteAuthorizationResult,
  type MockAuthenticatedRole,
  type MockAuthRole,
  type MockAuthState,
  type MockAuthUser,
  type MockSession,
} from "./mock-auth";

export {
  APP_ROUTE_ACCESS_POLICIES,
  canAccessAdminSectionRole,
  canManageAccessControlRole,
  canManageAdminSectionRole,
  canManageBooksRole,
  canManageBorrowingsRole,
  canManageCategoriesRole,
  canManageInventoryRole,
  canManageUsersRole,
  canViewFinancialsRole,
  createEmptyResolvedAdminSectionPermissions,
  getAdminSectionFromPathname,
  getAdminSectionLabel,
  getAdminSectionRoute,
  getRouteAccessPolicy,
  getResolvedAdminSectionPermissions,
  getResolvedAdminSectionPermissionsForDefaults,
  roleAdminSectionDefaults,
  type AppRouteAccessAudience,
  type AppRouteAccessLevel,
  type AppRouteAccessPolicy,
  type ResolvedAppSectionPermission,
  type ResolvedAppSectionPermissions,
} from "./permissions";

export {
  getAppRoleAccountLabel,
  getAppRoleDisplayLabel,
  getDefaultRedirectForAppRole,
  hasAdminAccessRole,
  isAdminRole,
  isAppUserRole,
  isEmployeeRole,
  isFinancialRole,
  isMemberRole,
  isSuperAdminRole,
  isStaffRole,
  type AdminAccessRole,
} from "./roles";

export type {
  AppAdminSection,
  AppAdminSectionAccess,
  AppAdminSectionPermission,
} from "./app-user-model";

export {
  APP_ADMIN_SECTION_VALUES,
  APP_USER_ROLE_VALUES,
} from "./app-user-model";

export {
  getMockAppUserRecord,
  type AppUserRecord,
  type AppUserRole,
  type AppUserStatus,
} from "./app-users";
