import { BookCopy, CircleDollarSign, Clock3, Users } from "lucide-react";

import type {
  AdminBorrowingRecord,
  AdminBorrowingsMetric,
  AdminBorrowingsTab,
} from "./types";

export const adminBorrowingsTabs: ReadonlyArray<{
  label: string;
  value: AdminBorrowingsTab;
}> = [
  { label: "Active", value: "active" },
  { label: "Pending", value: "pending" },
  { label: "Returned", value: "returned" },
  { label: "Overdue", value: "overdue" },
];

export const adminBorrowingsMetrics: ReadonlyArray<AdminBorrowingsMetric> = [
  {
    label: "Open borrowings",
    value: "128",
    supportingText: "Across all branches",
    icon: BookCopy,
  },
  {
    label: "Pending pickups",
    value: "14",
    supportingText: "Ready or nearly ready today",
    icon: Clock3,
  },
  {
    label: "Cash due",
    value: "$41.50",
    supportingText: "Settled onsite only",
    icon: CircleDollarSign,
  },
  {
    label: "Members affected",
    value: "63",
    supportingText: "Across active and overdue tabs",
    icon: Users,
  },
];

export const adminBorrowingsRecords: ReadonlyArray<AdminBorrowingRecord> = [
  {
    id: "borrowing-clean-code",
    bookId: "clean-code",
    bookTitle: "Clean Code",
    bookAuthor: "Robert C. Martin",
    memberName: "Sara Chehab",
    memberPlan: "Community plan",
    branch: "Downtown",
    dueLabel: "Due",
    dueValue: "Apr 5",
    feeCents: 0,
    paymentLabel: "No fee",
    paymentTone: "success",
    statusLabel: "Checked out",
    statusTone: "success",
    tab: "active",
  },
  {
    id: "borrowing-1984",
    bookId: "1984",
    bookTitle: "1984",
    bookAuthor: "George Orwell",
    memberName: "Noor Haddad",
    memberPlan: "Student plan",
    branch: "Hamra",
    dueLabel: "Pickup by",
    dueValue: "Today 6:00 PM",
    feeCents: 250,
    paymentLabel: "Cash at pickup",
    paymentTone: "warning",
    statusLabel: "Ready for pickup",
    statusTone: "info",
    tab: "pending",
  },
  {
    id: "borrowing-sapiens",
    bookId: "sapiens",
    bookTitle: "Sapiens",
    bookAuthor: "Yuval Noah Harari",
    memberName: "Karim Youssef",
    memberPlan: "Community plan",
    branch: "Downtown",
    dueLabel: "Returned",
    dueValue: "Apr 1",
    feeCents: 200,
    paymentLabel: "Settled in cash",
    paymentTone: "success",
    statusLabel: "Returned",
    statusTone: "neutral",
    tab: "returned",
  },
  {
    id: "borrowing-meditations",
    bookId: "meditations",
    bookTitle: "Meditations",
    bookAuthor: "Marcus Aurelius",
    memberName: "Lina Saab",
    memberPlan: "Reader plan",
    branch: "Byblos",
    dueLabel: "Overdue since",
    dueValue: "Mar 31",
    feeCents: 0,
    paymentLabel: "Reminder sent",
    paymentTone: "danger",
    statusLabel: "Overdue",
    statusTone: "danger",
    tab: "overdue",
  },
  {
    id: "borrowing-time",
    bookId: "brief-history-time",
    bookTitle: "A Brief History of Time",
    bookAuthor: "Stephen Hawking",
    memberName: "Jad Fares",
    memberPlan: "Research plan",
    branch: "Hamra",
    dueLabel: "Due",
    dueValue: "Apr 3",
    feeCents: 350,
    paymentLabel: "Collect at return",
    paymentTone: "warning",
    statusLabel: "Due soon",
    statusTone: "warning",
    tab: "active",
  },
];
