export {
  getMongoClient,
  getMongoDatabaseName,
  hasExplicitMongoDatabaseName,
  isMongoConfigured,
} from "./client";

export {
  checkDatabaseReadiness,
  type DatabaseDiagnostic,
  type DatabaseDiagnosticCode,
  type DatabaseDiagnosticLevel,
  type DatabaseReadinessResult,
} from "./core/diagnostics";

export {
  initializeDatabase,
  type DatabaseInitializationResult,
} from "./core/init";

export {
  COLLECTIONS,
  getBookCopiesCollection,
  getBooksCollection,
  getBorrowRequestsCollection,
  getCategoriesCollection,
  getCollection,
  getCollections,
  getUsersCollection,
  type CollectionName,
  type MongoCollections,
} from "./collections";

export type {
  AppUserRole,
  AppUserStatus,
  BaseDocument,
  BookCopyCondition,
  BookCopyDocument,
  BookCopyId,
  BookCopyStatus,
  BookDocument,
  BookId,
  BookPublicationMetadata,
  BookStatus,
  BorrowDurationType,
  BorrowRequestDocument,
  BorrowRequestId,
  BorrowRequestStatus,
  CategoryDocument,
  CategoryId,
  CreateBookCopyInput,
  CreateBookInput,
  CreateBorrowRequestInput,
  CreateCategoryInput,
  CreateUserInput,
  DatabaseId,
  PaymentMethod,
  PaymentStatus,
  UpdateBookCopyInput,
  UpdateBookInput,
  UpdateBorrowRequestInput,
  UpdateCategoryInput,
  UpdateUserInput,
  UserDocument,
  UserId,
} from "./models";

export {
  AppUserRoleSchema,
  AppUserStatusSchema,
  BaseDocumentSchema,
  BookCopyConditionSchema,
  BookCopyDocumentSchema,
  BookCopyStatusSchema,
  BookDocumentSchema,
  BookPublicationMetadataSchema,
  BookStatusSchema,
  BorrowDurationTypeSchema,
  BorrowRequestDocumentSchema,
  BorrowRequestStatusSchema,
  CategoryDocumentSchema,
  CreateBookCopyInputSchema,
  CreateBookInputSchema,
  CreateBorrowRequestInputSchema,
  CreateCategoryInputSchema,
  CreateUserInputSchema,
  DatabaseIdSchema,
  PaymentMethodSchema,
  PaymentStatusSchema,
  UpdateBookCopyInputSchema,
  UpdateBookInputSchema,
  UpdateBorrowRequestInputSchema,
  UpdateCategoryInputSchema,
  UpdateUserInputSchema,
  UserDocumentSchema,
} from "./models";