import type {
  AdminBookRecord,
  AdminBooksCategory,
  AdminBooksStatusFilter,
} from "./types";

export const adminBooksCategories: ReadonlyArray<AdminBooksCategory> = [
  "All",
  "Fiction",
  "Science",
  "History",
  "Philosophy",
  "Technology",
  "Art & Design",
  "Business",
  "Travel",
];

export const adminBooksStatusOptions: ReadonlyArray<{
  label: string;
  value: AdminBooksStatusFilter;
}> = [
  { label: "All states", value: "all" },
  { label: "Available", value: "healthy" },
  { label: "Low stock", value: "limited" },
  { label: "Out of stock", value: "archived" },
];

export const adminBooksCatalog: ReadonlyArray<AdminBookRecord> = [
  {
    id: "1984",
    title: "1984",
    author: "George Orwell",
    category: "Fiction",
    shelfCode: "FIC-19",
    totalCopies: 6,
    availableCopies: 4,
    feeCents: 250,
    coverTone: "brand",
    coverLabel: "1984",
    availabilityTone: "available",
    statusLabel: "Available",
    statusTone: "success",
  },
  {
    id: "brief-history-time",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Science",
    shelfCode: "SCI-08",
    totalCopies: 3,
    availableCopies: 1,
    feeCents: 350,
    coverTone: "ocean",
    coverLabel: "Time",
    availabilityTone: "limited",
    statusLabel: "Low stock",
    statusTone: "warning",
  },
  {
    id: "clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Technology",
    shelfCode: "TEC-14",
    totalCopies: 3,
    availableCopies: 1,
    feeCents: 0,
    coverTone: "stone",
    coverLabel: "Code",
    availabilityTone: "limited",
    statusLabel: "Low stock",
    statusTone: "warning",
  },
  {
    id: "into-the-wild",
    title: "Into the Wild",
    author: "Jon Krakauer",
    category: "Travel",
    shelfCode: "TRA-02",
    totalCopies: 4,
    availableCopies: 4,
    feeCents: 150,
    coverTone: "forest",
    coverLabel: "Wild",
    availabilityTone: "available",
    statusLabel: "Available",
    statusTone: "success",
  },
  {
    id: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    category: "Philosophy",
    shelfCode: "PHI-03",
    totalCopies: 2,
    availableCopies: 0,
    feeCents: 0,
    coverTone: "amber",
    coverLabel: "Mind",
    availabilityTone: "unavailable",
    statusLabel: "Out of stock",
    statusTone: "danger",
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "History",
    shelfCode: "HIS-21",
    totalCopies: 5,
    availableCopies: 2,
    feeCents: 200,
    coverTone: "rose",
    coverLabel: "Past",
    availabilityTone: "limited",
    statusLabel: "Circulating",
    statusTone: "info",
  },
  {
    id: "thinking-fast-slow",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Business",
    shelfCode: "BUS-07",
    totalCopies: 5,
    availableCopies: 3,
    feeCents: 300,
    coverTone: "brand",
    coverLabel: "Mindset",
    availabilityTone: "available",
    statusLabel: "Available",
    statusTone: "success",
  },
  {
    id: "ways-seeing",
    title: "Ways of Seeing",
    author: "John Berger",
    category: "Art & Design",
    shelfCode: "ART-11",
    totalCopies: 2,
    availableCopies: 1,
    feeCents: 100,
    coverTone: "rose",
    coverLabel: "Seeing",
    availabilityTone: "limited",
    statusLabel: "Low stock",
    statusTone: "warning",
  },
];